development:
  adapter: postgresql
  database: clockwork_dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: clockwork_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: clockwork
  pool: 5
  timeout: 5000