p1 = Post.create!(header: "Service Crew", company: "ShuKuu Izakaya", salary: 10.0, description: "Housewives, Students are welcome!", location: "Chinatown", posting_date: "2015-08-11", job_date: "2016-01-03", owner_id: 45, status: "applied", expiry_date: "2016-01-02", duration: 7, start_time: "11:00")
c1 = Post.create!(header: "Weekend Dishwasher", company: "DIS Manpower Pte Ltd", salary: 9.5, description: "Job Scope - clear some stuff, load dishes into machine, unload dry store", location: "Orchard", posting_date: "2015-07-21", job_date: "2015-08-22", owner_id: 45, status: "completed", expiry_date: "2015-08-21", duration: 2, start_time: "11:00")
e1 = Post.create!(header: "Cafe Service Crew", company: "TCC Manpower Pte Ltd", salary: 9.2, description: "Job Scope - Serving food and drinks, Clearing or just restaurant food runner duties, Basic Housekeeping duties", location: "Suntec City", posting_date: "2015-08-21", job_date: "2015-08-24", owner_id: 45, status: "expired", expiry_date: "2015-08-23", duration: 3, start_time: "11:00")
p2 = Post.create!(header: "Poolside Bar Service", company: "Henry Almighty", salary: 8.5, description: "Can commit 5 or more days per week and for 3 MONTHS", location: "Suntec City", posting_date: "2015-08-21", job_date: "2015-09-25", owner_id: 45, status: "listed", expiry_date: "2015-09-24", duration: 2, start_time: "11:00")
c2 = Post.create!(header: "Japanese Spaghetti House", company: "Japanese Spaghetti House", salary: 9.0, description: "Japanese Spaghetti House Part-time Service crew Job Scope: Greeting customers, Serving food and drinks Top up drinks Clearing empty dishes", location: "Tanjong Pagar", posting_date: "2015-08-01", job_date: "2015-09-27", owner_id: 45, status: "completed", expiry_date: "2015-09-26", duration: 8, start_time: "11:00")
c3 = Post.create!(header: "Server", company: "tcchr", salary: 10.5, description: "SERVING OF FOOD AND DRINKS", location: "Sentosa", posting_date: "2015-08-01", job_date: "2015-08-27", owner_id: 45, status: "completed", expiry_date: "2015-08-26", duration: 8, start_time: "11:00")
c4 = Post.create!(header: "Service Crew", company: "Cool Orchard Clubs", salary: 8.1, description: "Operating 7 F&B Restaurants, Bistros & Bars", location: "Orchard", posting_date: "2015-08-01", job_date: "2015-08-28", owner_id: 45, status: "completed", expiry_date: "2015-08-27", duration: 1, start_time: "11:00")
c5 = Post.create!(header: "Service Crew", company: "Western Restaurant", salary: 8.0, description: "Taking Orders, Serving Food & Drinks & Clearing Tables", location: "Toa Payoh", posting_date: "2015-08-01", job_date: "2015-09-29", owner_id: 45, status: "completed", expiry_date: "2015-08-28", duration: 3, start_time: "11:00")
c6 = Post.create!(header: "Waiter", company: "Japanese Restaurant", salary: 9.0, description: "Taking Orders, Serving Food & Drinks & Clearing Tables", location: "Buona Vista", posting_date: "2015-08-01", job_date: "2015-08-30", owner_id: 45, status: "completed", expiry_date: "2015-08-29", duration: 8, start_time: "11:00")
Post.create!(header: "Hotel Cafe", company: "Studio M Hotel", salary: 12.0, description: "Responsibilities: - Greet and welcome guests, assist in taking F&B orders and ensure prompt serving", location: "Tanglin", posting_date: "2015-08-21", job_date: "2015-09-21", owner_id: 45, status: "expired", expiry_date: "2015-08-20", duration: 8, start_time: "11:00")
p3 = Post.create!(header: "Restaurant Crew", company: "DIS Manpower Pte Ltd", salary: 9.0, description: "Job Scope - Serving food and drinks, Clearing or just restaurant food runner duties, Basic Housekeeping duties", location: "Boat Quay", posting_date: "2015-08-21", job_date: "2015-09-23", owner_id: 45, status: "applied", expiry_date: "2015-09-22", duration: 8, start_time: "11:00")
Post.create!([
  {header: "Restaurant Crew", company: "DIS Manpower Pte Ltd", salary: 9.0, description: "Job Scope - Serving food and drinks, Clearing or just restaurant food runner duties, Basic Housekeeping duties", location: "Raffles Place", posting_date: "2015-08-01", job_date: "2015-09-26", owner_id: 45, status: "applied", expiry_date: "2015-09-25", duration: 8, start_time: "11:00"},
  {header: "Banquet Server", company: "TCCHR", salary: 8.0, description: "WE ARE HIRING !!! PT & FT Server @5* Hotel", location: "City Hall", posting_date: "2015-08-21", job_date: "2015-08-20", owner_id: 45, status: "completed", expiry_date: "2015-08-19", duration: 8, start_time: "11:00"},
  {header: "Frozen Yogurt Server", company: "Mission Juice", salary: 10.0, description: "If you are looking to join an energetic, fun and vibrant team that offers on the job training and support, then join Mission Juice today! If you value commitment, professionalism and have a keen interest in learning and enhancing your skill set, join the Mission Juice team today! If you want to be among a group of people who want to progress together by working hard and want a place where you can excel and to find your full potential, then join the Mission Juice team today! If you have passion to serve and to make the world a happier place one juice at a time, then we want you! We want to hear from you! Full Time and Part time available!", location: "Tanjong Pagar", posting_date: "2015-08-01", job_date: "2015-09-26", owner_id: 45, status: "applied", expiry_date: "2015-09-25", duration: 8, start_time: "11:00"},
  {header: "Customer Service", company: "Next Door Cafe & Taverna", salary: 10.0, description: "We are seeking enthusiastic people to work with on full-time or part-time basis. Some experience in F&B service would be nice although not necessary. If you enjoy communicating with people and you are located in the East, come meet with us!", location: "Bedok", posting_date: "2015-08-11", job_date: "2015-01-02", owner_id: 45, status: "completed", expiry_date: "2015-01-01", duration: 8, start_time: "11:00"}
])
Matching.create!([
  {applicant_id: 75, post_id: c1.id, status: "completed", user_rating: -1, comments: "Came late left early"},
  {applicant_id: 75, post_id: c2.id, status: "completed", user_rating: -1, comments: "Not very good worker"},
  {applicant_id: 75, post_id: c3.id, status: "completed", user_rating: 0, comments: nil},
  {applicant_id: 75, post_id: c4.id, status: "completed", user_rating: 1, comments: "Hardworking, first to work everyday"},
  {applicant_id: 75, post_id: c5.id, status: "completed", user_rating: 1, comments: "Friendly person"},
  {applicant_id: 75, post_id: c6.id, status: "completed", user_rating: 1, comments: "Fun to work with"},
  {applicant_id: 75, post_id: p1.id, status: "pending", user_rating: 0, comments: nil},
  {applicant_id: 75, post_id: p2.id, status: "offered", user_rating: 0, comments: nil},
  {applicant_id: 75, post_id: p3.id, status: "hired", user_rating: 0.0, comments: nil}
])